# Generated by Django 4.2.6 on 2023-11-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default=True, upload_to='photos/doctors'),
        ),
    ]
